/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gapuz_program;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author CL2-PC
 */
public class ADMIN extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> rowSorter;
    
    private boolean isEditing = false;
    private String selectedOldPetId = "";

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
        parentpanel.add(detailpanel, "detailpanel");
        parentpanel.add(databasepanel, "databasepanel");
        conn = MsConnectAccess.conn();
        filterTableData();
        setFieldsEditable(true); // Must be true so fields are open by default
    }
    /**
     * Safe helper method to retrieve string values from JTable model without risking NullPointerException
     */
    private String getModelValue(int modelRow, int column) {
        Object value = jTable1.getModel().getValueAt(modelRow, column);
        return (value != null) ? value.toString() : "";
    }
    

    private void filterTableData() {
    String searchText = txt7.getText().trim();
        
    Object selectedItem = jComboBox1.getSelectedItem();
    String selectedCategory = (selectedItem != null) ? selectedItem.toString() : "";

    // Explicitly query columns with square brackets to match Access naming
    StringBuilder sql = new StringBuilder("SELECT [Pet_ID], [Pet_Name], [Breed], [Pet_Age], [Owner_Name], [Contact_Number], [Diagnosis_Notes], [All Pet Types] FROM [TABLE_RECORD] WHERE 1=1");
    
    boolean hasCategoryFilter = !selectedCategory.isEmpty() 
        && !selectedCategory.equals("Type of Pets") 
        && !selectedCategory.equals("All Pet Types") 
        && !selectedCategory.equals("All Type of Pets") 
        && !selectedCategory.equals("Type of Pet");

    if (hasCategoryFilter) {
        sql.append(" AND [All Pet Types] = ?");
    }

    boolean hasSearchText = !searchText.isEmpty();
    if (hasSearchText) {
        sql.append(" AND ([Pet_ID] LIKE ? OR [Pet_Name] LIKE ? OR [Owner_Name] LIKE ?)");
    }

    try (java.sql.Connection connLocal = MsConnectAccess.conn();
         java.sql.PreparedStatement pstmt = connLocal.prepareStatement(sql.toString())) {
        
        int paramIndex = 1;
        
        if (hasCategoryFilter) {
            pstmt.setString(paramIndex++, selectedCategory);
        }
        
        if (hasSearchText) {
            String wildcardSearch = "%" + searchText + "%";
            pstmt.setString(paramIndex++, wildcardSearch); // For Pet_ID
            pstmt.setString(paramIndex++, wildcardSearch); // For Pet_Name
            pstmt.setString(paramIndex++, wildcardSearch); // For Owner_Name
        }
        
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            jTable1.setModel(buildTableModel(rs));
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Filter error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }
    public static javax.swing.table.DefaultTableModel buildTableModel(java.sql.ResultSet rs) throws java.sql.SQLException {
    java.sql.ResultSetMetaData metaData = rs.getMetaData();
    
    // Names of columns
        int columnCount = metaData.getColumnCount();
        java.util.Vector<String> columnNames = new java.util.Vector<>();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }
        
        // Data of the table
        java.util.Vector<java.util.Vector<Object>> data = new java.util.Vector<>();
        while (rs.next()) {
            java.util.Vector<Object> vector = new java.util.Vector<>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        
        return new javax.swing.table.DefaultTableModel(data, columnNames);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentpanel = new javax.swing.JPanel();
        detailpanel = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        lblrecdet = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        databasepanel = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        lbldatabase = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentpanel.setBackground(new java.awt.Color(102, 102, 102));
        parentpanel.setLayout(new java.awt.CardLayout());

        detailpanel.setBackground(new java.awt.Color(102, 102, 102));
        detailpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        detailpanel.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, 40));

        jLabel1.setText("Pet ID:");
        detailpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel2.setText("Pet Name:");
        detailpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel3.setText("Breed:");
        detailpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("Owner name:");
        detailpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        detailpanel.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 220, -1));
        detailpanel.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 220, -1));

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        detailpanel.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, -1));
        detailpanel.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, -1));
        detailpanel.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, -1));

        btnview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnview.setText("VIEW");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        detailpanel.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 120, 40));

        jLabel5.setText("Pet Age:");
        detailpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setText("Contact Number:");
        detailpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txta1.setColumns(20);
        txta1.setRows(5);
        jScrollPane2.setViewportView(txta1);

        detailpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 260, 100));

        jLabel7.setText("Diagnosis/Notes:");
        detailpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        detailpanel.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, -1));

        lblrecdet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblrecdet.setText("PET RECORD DETAILS");
        detailpanel.add(lblrecdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, -1));

        btnlogout.setBackground(new java.awt.Color(153, 0, 0));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setText("LOG OUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        detailpanel.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Type--", "Cat", "Dog" }));
        detailpanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, -1));

        jLabel9.setText("Type of Pet:");
        detailpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        parentpanel.add(detailpanel, "card2");

        databasepanel.setBackground(new java.awt.Color(204, 204, 204));
        databasepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedit.setBackground(new java.awt.Color(0, 102, 0));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        databasepanel.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 90, 40));

        btndelete.setBackground(new java.awt.Color(204, 0, 0));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        databasepanel.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 90, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet_ID", "Pet_Name", "Breed", "Pet_Age", "Owner_Name", "Contact_Number", "Diagnosis_Notes", "ALL_Pet_Types"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        databasepanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 810, 360));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Type of Pets", "Cat", "Dog" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        databasepanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Search Record:");
        databasepanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        databasepanel.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, -1));

        lbldatabase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbldatabase.setText("PET RECORD DATABASE");
        databasepanel.add(lbldatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        btnback.setBackground(new java.awt.Color(153, 0, 0));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        databasepanel.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 30));

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        databasepanel.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        parentpanel.add(databasepanel, "card2");

        getContentPane().add(parentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1290, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String petId = txt1.getText().trim();
String name = txt2.getText().trim(); 
String breed = txt3.getText().trim(); 
String age = txt4.getText().trim();
String owner = txt5.getText().trim();
String contact = txt6.getText().trim();
String notes = txta1.getText().trim();

String petType = "";
if (jComboBox2.getSelectedItem() != null) {
    petType = jComboBox2.getSelectedItem().toString().trim();
}

if (petId.isEmpty() || name.isEmpty() || owner.isEmpty()) {
    JOptionPane.showMessageDialog(rootPane, "Please fill in the required text fields!", "Warning", JOptionPane.WARNING_MESSAGE);
    return;
}

if (petType.isEmpty() || petType.equals("--Select Type--")) {
    JOptionPane.showMessageDialog(rootPane, "Please choose a type of pet!", "Warning", JOptionPane.WARNING_MESSAGE);
    jComboBox2.requestFocus();
    return;
}

// Fixed: Added square brackets [] around table and column names for UCanAccess compatibility
String sql = isEditing ? 
    "UPDATE [TABLE_RECORD] SET [Pet_Name]=?, [Breed]=?, [Pet_Age]=?, [Owner_Name]=?, [Contact_Number]=?, [Diagnosis_Notes]=?, [All Pet Types]=? WHERE [Pet_ID]=?" :
    "INSERT INTO [TABLE_RECORD] ([Pet_ID], [Pet_Name], [Breed], [Pet_Age], [Owner_Name], [Contact_Number], [Diagnosis_Notes], [All Pet Types]) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

try (java.sql.Connection connLocal = MsConnectAccess.conn();
     java.sql.PreparedStatement pstmt = connLocal.prepareStatement(sql)) {

    if (isEditing) {
        pstmt.setString(1, name);
        pstmt.setString(2, breed);
        pstmt.setString(3, age);
        pstmt.setString(4, owner);
        pstmt.setString(5, contact);
        pstmt.setString(6, notes);
        pstmt.setString(7, petType);
        pstmt.setString(8, selectedOldPetId);
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "Record updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        pstmt.setString(1, petId);
        pstmt.setString(2, name);
        pstmt.setString(3, breed);
        pstmt.setString(4, age);
        pstmt.setString(5, owner);
        pstmt.setString(6, contact);
        pstmt.setString(7, notes);
        pstmt.setString(8, petType);
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(rootPane, "New record added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    // Reset back to normal ADD mode
    isEditing = false;
    btnadd.setText("ADD");
    setFieldsEditable(true);

    // Clear input fields
    txt1.setText("");
    txt2.setText("");
    txt3.setText("");
    txt4.setText("");
    txt5.setText("");
    txt6.setText("");
    txta1.setText("");
    jComboBox2.setSelectedIndex(0);

    filterTableData();
    java.awt.CardLayout cardLayout = (java.awt.CardLayout) parentpanel.getLayout();
    cardLayout.show(parentpanel, "databasepanel");

} catch (java.sql.SQLException e) {
    JOptionPane.showMessageDialog(rootPane, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) parentpanel.getLayout();
        cardLayout.show(parentpanel, "databasepanel");
    }//GEN-LAST:event_btnviewActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a record from the database table first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int modelRow = jTable1.convertRowIndexToModel(selectedRow);

        selectedOldPetId = getModelValue(modelRow, 0);

        txt1.setText(selectedOldPetId);
        txt2.setText(getModelValue(modelRow, 1)); 
        txt3.setText(getModelValue(modelRow, 2)); 
        txt4.setText(getModelValue(modelRow, 3));
        txt5.setText(getModelValue(modelRow, 4));
        txt6.setText(getModelValue(modelRow, 5));
        txta1.setText(getModelValue(modelRow, 6));

        try {
            String typeVal = getModelValue(modelRow, 7);
            jComboBox2.setSelectedItem(typeVal != null ? typeVal.trim() : "--Select Type--");
        } catch (Exception e) {
            jComboBox2.setSelectedIndex(0);
        }

        isEditing = true;
        btnadd.setText("SAVE"); // Changes ADD to SAVE ONLY when Edit is clicked
        setFieldsEditable(true); // Unlocks fields for editing

        java.awt.CardLayout cardLayout = (java.awt.CardLayout) parentpanel.getLayout();
        cardLayout.show(parentpanel, "detailpanel");
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a record to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int modelRow = jTable1.convertRowIndexToModel(selectedRow);
        
        try {
            String id = getModelValue(modelRow, 0);

            int choice = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this record?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (choice == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM TABLE_RECORD WHERE Pet_ID=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Record deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                txt1.setText("");
                txt2.setText("");
                txt3.setText("");
                txt4.setText("");
                txt5.setText("");
                txt6.setText("");
                txta1.setText("");
                
                setFieldsEditable(false);
                btnedit.setText("EDIT");
                
                filterTableData();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Delete Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    
    private void setFieldsEditable(boolean editable) {
        txt1.setEditable(editable);
        txt1.setEnabled(editable);
        txt2.setEditable(editable);
        txt2.setEnabled(editable);
        txt3.setEditable(editable);
        txt3.setEnabled(editable);
        txt4.setEditable(editable);
        txt4.setEnabled(editable);
        txt5.setEditable(editable);
        txt5.setEnabled(editable);
        txt6.setEditable(editable);
        txt6.setEnabled(editable);
        txta1.setEditable(editable);
        txta1.setEnabled(editable);
        jComboBox2.setEnabled(editable);
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:            
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            int modelRow = jTable1.convertRowIndexToModel(row);

            txt1.setText(getModelValue(modelRow, 0));
            txt2.setText(getModelValue(modelRow, 1)); 
            txt3.setText(getModelValue(modelRow, 2)); 
            txt4.setText(getModelValue(modelRow, 3));
            txt5.setText(getModelValue(modelRow, 4));
            txt6.setText(getModelValue(modelRow, 5));
            txta1.setText(getModelValue(modelRow, 6));

            try {
                String typeVal = getModelValue(modelRow, 7);
                jComboBox2.setSelectedItem(typeVal != null ? typeVal.trim() : "--Select Type--");
            } catch (Exception e) {
                jComboBox2.setSelectedIndex(0);
            }

            setFieldsEditable(false); // Keep uneditable until Edit is clicked
            btnedit.setEnabled(true);
            btndelete.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        LOGIN loginWindow = new LOGIN();
        loginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        isEditing = false;
        btnadd.setText("ADD"); // Revert back to ADD when navigating back

        setFieldsEditable(true); 

        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        txta1.setText("");
        jComboBox2.setSelectedIndex(0); 

        java.awt.CardLayout cardLayout = (java.awt.CardLayout) parentpanel.getLayout();
        cardLayout.show(parentpanel, "detailpanel");
    }//GEN-LAST:event_btnbackActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        filterTableData();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        filterTableData();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnview;
    private javax.swing.JPanel databasepanel;
    private javax.swing.JPanel detailpanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbldatabase;
    private javax.swing.JLabel lblrecdet;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextArea txta1;
    // End of variables declaration//GEN-END:variables
}
