/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gapuz_program;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class LOGIN extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;

    public LOGIN() {
        initComponents();
        
        // 1. Connect to Access
        conn = MsConnectAccess.conn();
        
        // 2. Automatically create the login table and default accounts (Option 1)
        createLoginTableAndDefaultAccounts();
    }
    
    // This method automatically sets up Table1 and your 4 accounts so you don't have to do it manually at school
    private void createLoginTableAndDefaultAccounts() {
    try {
        Statement stmt = conn.createStatement();
        
        // --- 1. SETUP LOGIN TABLE (TABLE_LOGIN) ---
        try {
            stmt.execute("DROP TABLE TABLE_LOGIN");
        } catch (Exception ex) {
            // Ignore if TABLE_LOGIN doesn't exist yet
        }

        String createTableSQL = "CREATE TABLE TABLE_LOGIN (username VARCHAR(255) PRIMARY KEY, [password] VARCHAR(255))";
        stmt.execute(createTableSQL);

        // Insert your 4 default accounts
        String[] users = {"admin", "frontdesk1", "frontdesk2", "frontdesk3"};
        String[] password = {"admin123", "frontdesk1111", "frontdesk2222", "frontdesk3333"};

        for (int i = 0; i < users.length; i++) {
            String insertSQL = "INSERT INTO TABLE_LOGIN (username, [password]) VALUES (?, ?)";
            PreparedStatement insertPst = conn.prepareStatement(insertSQL);
            insertPst.setString(1, users[i]);
            insertPst.setString(2, password[i]);
            insertPst.executeUpdate();
        }

        // --- 2. SETUP PET RECORD TABLE (TABLE_RECORD) ---
        try {
            stmt.execute("DROP TABLE TABLE_RECORD");
        } catch (Exception ex) {
            // Ignore if TABLE_RECORD doesn't exist yet
        }

        // All text fields set to VARCHAR(255)
        String createTable2SQL = "CREATE TABLE TABLE_RECORD (" +
            "Pet_ID VARCHAR(255) PRIMARY KEY, " +
            "[Pet Name] VARCHAR(255), " +
            "[Breed] VARCHAR(255), " +
            "[Pet Age] VARCHAR(255), " +
            "[Owner Name] VARCHAR(255), " +
            "[Contact Number] VARCHAR(255), " +
            "[Diagnosis/Notes] VARCHAR(255))";
            stmt.execute(createTable2SQL);
        
        System.out.println("Tables configured successfully!");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        Jbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 140, 30));

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblusername.setText("Username:");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        lblpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpassword.setText("Password:");
        getContentPane().add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 140, 30));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbutton.setBackground(new java.awt.Color(0, 0, 204));
        Jbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbutton.setText("Log In");
        Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 660, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonActionPerformed
        String username = txt_username.getText().trim();
        char[] pass = txt_password.getPassword();
        String userpassword = String.valueOf(pass);
        
        try {
            String sqlquery = "SELECT * FROM Table1 WHERE username = ? AND [password] = ?";
            pst = conn.prepareStatement(sqlquery);
            pst.setString(1, username);
            pst.setString(2, userpassword);
            rs = pst.executeQuery();
            
            if (rs.next()) {
                // Credentials match!
                JOptionPane.showMessageDialog(null, "Login Successful!");

                // Open your CRUD dashboard window and close login
                ADMIN crudWindow = new ADMIN();
                crudWindow.setVisible(true);
                this.dispose(); 
                
            } else {
                // Wrong username or password
                JOptionPane.showMessageDialog(null, "Incorrect input: either username or password", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_JbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
