/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gapuz_program;

/**
 *
 * @author CL2-PC
 */
public class RPS_FORM extends javax.swing.JFrame {

    /**
     * Creates new form RPS_FORM
     */
    public RPS_FORM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtfield1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("DEG");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));
        getContentPane().add(txtfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 450, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SCIENTIFIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton2.setText("F-E");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 30));

        jButton3.setText("MC");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 40));

        jButton4.setText("MR");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 60, 40));

        jButton5.setText("M+");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, 40));

        jButton6.setText("M-");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, 40));

        jButton7.setText("Mv");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 210, 60, 40));

        jButton8.setText("⊿ Trigonometry ⋁");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 263, 130, 30));

        jButton9.setText("∫ Function ⋁");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 263, 140, 30));

        jButton10.setText("2ⁿᵈ");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        jButton11.setText("π");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 30));

        jButton12.setText("e");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 70, 30));

        jButton13.setText("C");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 70, 30));

        jButton14.setText("⌫");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 70, 30));

        jButton15.setText("x²");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jButton16.setText("¹/x");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, 30));

        jButton17.setText("|x|");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, 30));

        jButton18.setText("exp");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, 30));

        jButton19.setText("mod");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, 30));

        jButton20.setText("²√x");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        jButton21.setText("(");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 70, 30));

        jButton22.setText(")");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 70, 30));

        jButton23.setText("n!");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, 30));

        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton24.setText("÷");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 70, 30));

        jButton25.setText("xʸ");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 30));

        jButton26.setText("7");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 70, 30));

        jButton27.setText("8");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 70, 30));

        jButton28.setText("9");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 70, 30));

        jButton29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton29.setText("×");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 70, 30));

        jButton30.setText("10ˣ");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 30));

        jButton31.setText("4");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 70, 30));

        jButton32.setText("5");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 70, 30));

        jButton33.setText("6");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 70, 30));

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton34.setText("−");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 70, 30));

        jButton35.setText("log");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 30));

        jButton36.setText("1");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 70, 30));

        jButton37.setText("2");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 70, 30));

        jButton38.setText("3");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 70, 30));

        jButton39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton39.setText("+");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 70, 30));

        jButton40.setText("MS");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 60, 40));

        jButton41.setText("In");
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 70, 30));

        jButton42.setText("+/-");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 70, 30));

        jButton43.setText("0");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 70, 30));

        jButton44.setText(".");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 70, 30));

        jButton45.setBackground(new java.awt.Color(0, 0, 255));
        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton45.setText("=");
        getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS_FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS_FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtfield1;
    // End of variables declaration//GEN-END:variables
}
